### PR TITLE
delete text in N load plotting page

### PR DESCRIPTION
**Pull request by giorgichi**
- removed "Frequently Asked Questions" and "Observation Site Collection Interval" at the bottom of the page
- removed csv and Excel download options for data
- removed missing value selection

Related to: #isudatateam/datateam/issues/225

### CODE REVIEW

**Comment by giorgichi** [comment]
@akrherz, we might need to (a) completely eliminate **View and Download Options** or (b) add figure download option to it. Currently, figure download is available via the _**Chart context menu**_.

**Comment by giorgichi** [comment]
#235

**Comment by akrherz** [comment]
Thanks for your efforts here.  I'm going to put some more commits ontop of it as I don't think some of your changes will work properly.

**Comment by akrherz** [comment]
closing in favor of #239

**Pull request closed without merging**
